# Data prep

In [2]:
import numpy as np
import pandas as pd

---
## Posts

In [3]:
# import posts data
scifi_posts = pd.read_csv('../data/scifi_posts_10000.csv', index_col=0)
fantasy_posts = pd.read_csv('../data/fantasy_posts_10000.csv', index_col=0)

/Users/yuli/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (68) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/Users/yuli/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (84) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
scifi_posts.head(2)

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,media,media_embed,secure_media,secure_media_embed,author_flair_background_color,author_flair_text_color,poll_data,banned_by,edited,gilded
0,[],False,spiray3904,NaN,[],NaN,text,t2_8bsso8w9,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,Efficient-Gold-6216,NaN,[],NaN,text,t2_6llwdb7g,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
fantasy_posts.head(2)

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,secure_media,secure_media_embed,is_gallery,collections,gallery_data,edited,gilded,author_cakeday,banned_by,distinguished
0,[],False,Emotional_Object3967,NaN,[],NaN,text,t2_aijrbe8w,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,mpc3980,NaN,[],NaN,text,t2_1qb7wqce,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# combine two dataframes into one
posts_all = pd.concat([scifi_posts[:5000], fantasy_posts[:5000]])

In [7]:
# keeep only necessary columns
posts = posts_all[['title', 'selftext', 'subreddit']]
posts

,title,selftext,subreddit
0,Follow me,NaN,scifi
1,"Scientific research should be ethical, not evil..",NaN,scifi
2,Book recommendations for series similar to Leo...,"Basically, a series where an individual or gr...",scifi
3,Recommendations for fantasy that turns out to ...,NaN,scifi
4,Scifi Horror recommendation,[removed],scifi
...,...,...,...
95,What evil fantasy characters scared you the most?,NaN,Fantasy
96,"/r/Fantasy Writing Wednesday - December 30, 2020",The weekly Writing Wednesday thread is the pla...,Fantasy
97,/r/Fantasy - Daily Recommendation Requests and...,This thread is to be used for recommendation r...,Fantasy
98,"My 2020 reading ""awards""",Inspired by the recent suite of 2020-wrap up p...,Fantasy
99,How far in did it take you to really get into ...,"For some unknown reason, I am struggling to en...",Fantasy

In [8]:
# reset index
posts.reset_index(inplace=True)
posts.head(3)

,index,title,selftext,subreddit
0,0,Follow me,NaN,scifi
1,1,"Scientific research should be ethical, not evil..",NaN,scifi
2,2,Book recommendations for series similar to Leo...,"Basically, a series where an individual or gr...",scifi

In [9]:
# drop old index
posts.drop(columns=['index'], inplace=True)

/Users/yuli/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [10]:
posts

,title,selftext,subreddit
0,Follow me,NaN,scifi
1,"Scientific research should be ethical, not evil..",NaN,scifi
2,Book recommendations for series similar to Leo...,"Basically, a series where an individual or gr...",scifi
3,Recommendations for fantasy that turns out to ...,NaN,scifi
4,Scifi Horror recommendation,[removed],scifi
...,...,...,...
9995,What evil fantasy characters scared you the most?,NaN,Fantasy
9996,"/r/Fantasy Writing Wednesday - December 30, 2020",The weekly Writing Wednesday thread is the pla...,Fantasy
9997,/r/Fantasy - Daily Recommendation Requests and...,This thread is to be used for recommendation r...,Fantasy
9998,"My 2020 reading ""awards""",Inspired by the recent suite of 2020-wrap up p...,Fantasy
9999,How far in did it take you to really get into ...,"For some unknown reason, I am struggling to en...",Fantasy

In [11]:
# save to csv
posts.to_csv('../data/posts.csv')

---
## Comments

In [15]:
# import comments data
scifi_comments = pd.read_csv('../data/scifi_comments_10000.csv', index_col=0)
fantasy_comments = pd.read_csv('../data/fantasy_comments_10000.csv', index_col=0)

In [16]:
scifi_comments.head(2)

,all_awardings,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,author_flair_template_id,author_flair_text,author_flair_text_color,author_flair_type,...,score,send_replies,stickied,subreddit,subreddit_id,total_awards_received,treatment_tags,edited,author_cakeday,distinguished
0,[],NaN,CheatMaple,NaN,NaN,[],NaN,NaN,NaN,text,...,2,True,False,scifi,t5_2qh2z,0,[],NaN,NaN,NaN
1,[],NaN,CheatMaple,NaN,NaN,[],NaN,NaN,NaN,text,...,1,True,False,scifi,t5_2qh2z,0,[],NaN,NaN,NaN

In [17]:
fantasy_comments.head(2)

,all_awardings,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,author_flair_template_id,author_flair_text,author_flair_text_color,author_flair_type,...,send_replies,stickied,subreddit,subreddit_id,top_awarded_type,total_awards_received,treatment_tags,edited,author_cakeday,distinguished
0,[],NaN,BearbertDondarrion,NaN,NaN,[],NaN,NaN,NaN,text,...,True,False,Fantasy,t5_2qknd,NaN,0,[],NaN,NaN,NaN
1,[],NaN,Itrulade,NaN,NaN,[],NaN,NaN,NaN,text,...,True,False,Fantasy,t5_2qknd,NaN,0,[],NaN,NaN,NaN

In [19]:
# combine two dataframes into one
# cut to 5000 rows each
comments_all = pd.concat([scifi_comments[:5000], fantasy_comments[:5000]])

In [20]:
comments = comments_all[['body', 'subreddit']]
comments

                                                 body subreddit
0                                       use subtitles     scifi
1                         For neither ever, nor never     scifi
2                         It reminds me of Fringe too     scifi
3   Saw S01 in English, had to resort to subtitles...     scifi
4   When season 2 was released, all the recaps I h...     scifi
..                                                ...       ...
95  Didn't Orson Scott Card donate his money to an...   Fantasy
96  :( I liked the first.  The second was weaker b...   Fantasy
97  Lmao he is a bit of a chad honestly\n\nYA: You...   Fantasy
98  It's not at all terrible, it's really goddamn ...   Fantasy
99  I have not read any of the others on your list...   Fantasy

[10000 rows x 2 columns]

In [21]:
# reset index
comments.reset_index(inplace=True)
comments.head(3)

   index                         body subreddit
0      0                use subtitles     scifi
1      1  For neither ever, nor never     scifi
2      2  It reminds me of Fringe too     scifi

In [22]:
# drop old index
comments.drop(columns=['index'], inplace=True)

/Users/yuli/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [23]:
comments

                                                   body subreddit
0                                         use subtitles     scifi
1                           For neither ever, nor never     scifi
2                           It reminds me of Fringe too     scifi
3     Saw S01 in English, had to resort to subtitles...     scifi
4     When season 2 was released, all the recaps I h...     scifi
...                                                 ...       ...
9995  Didn't Orson Scott Card donate his money to an...   Fantasy
9996  :( I liked the first.  The second was weaker b...   Fantasy
9997  Lmao he is a bit of a chad honestly\n\nYA: You...   Fantasy
9998  It's not at all terrible, it's really goddamn ...   Fantasy
9999  I have not read any of the others on your list...   Fantasy

[10000 rows x 2 columns]

In [26]:
# save to csv
comments.to_csv('../data/comments.csv')