# Data collection - scifi

In [1]:
import numpy as np
import pandas as pd
import requests
import time

## Set URL, params and get_data function

In [2]:
# st base url and params
url_sub = 'https://api.pushshift.io/reddit/search/submission'
url_com = 'https://api.pushshift.io/reddit/search/comment'

params = {
    'subreddit': 'scifi',
    'size': 100,
    'before': None,
}

In [3]:
def get_data(url, params):
    
    """
    This finction makes a request and pulls data
    and returns a dataframe from a response.
    """
    
    res = requests.get(url, params)
    data = res.json()
    posts = data['data']
    df = pd.DataFrame(posts) 
    # the line below attributed to Jacob
    params['before'] = df.iloc[-1]['created_utc']
    
    print(params['before'])
    print(df.shape[0])

    time.sleep(5.0)
    
    return df

---
## Get scifi posts and comments

In [4]:
# get posts
scifi_posts = []

for i in range(100):
    scifi_posts.append(get_data(url_sub, params))

1619786218
100
1619510486
100
1619282186
100
1619103366
100
1618804261
100
1618550512
100
1617888047
100
1617518078
100
1617268478
100
1616971711
100
1615822121
100
1615555620
100
1615246227
100
1614741204
100
1614308705
100
1614035686
100
1613779734
100
1613390829
100
1613167552
100
1612891805
100
1612338544
100
1612108191
100
1611938779
100
1611555148
100
1611260979
100
1610861206
100
1610638125
100
1610311498
100
1609979662
100
1609758839
100
1609553467
100
1609270356
100
1609004718
100
1608684937
100
1608417389
100
1608142701
100
1607826166
100
1607663479
100
1607425476
100
1607186420
100
1606906764
100
1606657933
100
1606469219
100
1606173625
100
1605975138
100
1605731139
100
1605416486
100
1605112888
100
1604826898
100
1604414373
100
1604150300
100
1603831865
100
1603561345
100
1603323208
100
1602950724
100
1602687712
100
1602448791
100
1602211451
100
1601938065
100
1601716005
100
1601343228
100
1601107702
100
1600733318
100
1600482565
100
1600179638
100
1599920795
100
1599678466
100
1599461119
100
1599235663
100
1598993207
100
1598719792
100
1598469653
100
1598177798
100
1597964117
100
1597669815
100
1597423087
100
1597071129
100
1596832776
100
1596503516
100
1596287083
100
1595926803
100
1595671418
100
1595322394
100
1595055525
100
1594719239
100
1594502310
100
1594253494
100
1593909254
100
1593571404
100
1593285023
100
1593096501
100
1592850329
100
1592515902
100
1592200535
100
1592051001
100
1591749431
100
1591495514
100
1591204988
100
1590856060
100
1590531102
100

In [5]:
scifi_p = pd.concat(scifi_posts)
scifi_p.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,media,media_embed,secure_media,secure_media_embed,author_flair_background_color,author_flair_text_color,poll_data,banned_by,edited,gilded
0,[],False,spiray3904,None,[],None,text,t2_8bsso8w9,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,Efficient-Gold-6216,None,[],None,text,t2_6llwdb7g,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,jointly-epic,None,[],None,text,t2_bawoveyl,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,Silverscoundrel,None,[],None,text,t2_j2w5bd1,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,low-key4991,None,[],None,text,t2_7sv8pwss,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
scifi_p.shape

(10000, 79)

In [7]:
# save posts df
scifi_p.to_csv('../data/scifi_posts_10000.csv')

In [8]:
# get comments
scifi_comments = []

for i in range(100):
    scifi_comments.append(get_data(url_com, params))

1590516280
100
1590486721
100
1590449284
100
1590428731
100
1590392049
100
1590348183
100
1590321485
100
1590298766
100
1590274232
100
1590251706
100
1590235406
100
1590220860
100
1590196431
100
1590181692
100
1590165424
100
1590148264
100
1590118527
100
1590105323
100
1590097283
100
1590091581
100
1590085676
100
1590071320
100
1590041914
100
1590023088
100
1590011667
100
1590003407
100
1589997953
100
1589991355
100
1589985758
100
1589979053
100
1589967565
100
1589947542
100
1589939097
100
1589930833
100
1589905151
100
1589888186
100
1589862755
100
1589848972
100
1589803588
100
1589754613
100
1589736244
100
1589721385
100
1589685094
100
1589655006
100
1589639973
100
1589615645
100
1589586139
100
1589572336
100
1589562263
100
1589555752
100
1589534205
100
1589511114
100
1589500159
100
1589490193
100
1589482539
100
1589476382
100
1589471875
100
1589468982
100
1589465925
100
1589450670
100
1589421652
100
1589398146
100
1589335448
100
1589296466
100
1589238064
100
1589225901
100
1589212944
100
1589200104
100
1589176270
100
1589168080
100
1589162988
100
1589157870
100
1589149303
100
1589143218
100
1589121574
100
1589081157
100
1589045587
100
1589025971
100
1588994518
100
1588972587
100
1588960438
100
1588949340
100
1588904124
100
1588873475
100
1588860263
100
1588835935
100
1588813865
100
1588804862
100
1588784237
100
1588765473
100
1588733761
100
1588705899
100
1588696221
100
1588684775
100
1588659985
100
1588637638
100
1588626756
100
1588619036
100
1588604654
100
1588591785
100

In [9]:
scifi_c = pd.concat(scifi_comments)
scifi_c.head()

,all_awardings,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,author_flair_template_id,author_flair_text,author_flair_text_color,author_flair_type,...,score,send_replies,stickied,subreddit,subreddit_id,total_awards_received,treatment_tags,edited,author_cakeday,distinguished
0,[],None,CheatMaple,None,None,[],None,None,None,text,...,2,True,False,scifi,t5_2qh2z,0,[],NaN,NaN,NaN
1,[],None,CheatMaple,None,None,[],None,None,None,text,...,1,True,False,scifi,t5_2qh2z,0,[],NaN,NaN,NaN
2,[],None,CheatMaple,None,None,[],None,None,None,text,...,4,True,False,scifi,t5_2qh2z,0,[],NaN,NaN,NaN
3,[],None,tb21666,None,None,[],None,None,None,text,...,2,True,False,scifi,t5_2qh2z,0,[],NaN,NaN,NaN
4,[],None,AdamPalma,None,None,[],None,None,None,text,...,2,True,False,scifi,t5_2qh2z,0,[],NaN,NaN,NaN

In [10]:
scifi_c.shape

(10000, 36)

In [11]:
# save dataframe as csv
scifi_c.to_csv('../data/scifi_comments_10000.csv')